package com.odevs.thassosscooterandatwfinder.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class Strings(
    val appName: String,
    val scooter: String,
    val restaurants: String,
    val beaches: String,
    val vehicle_type: String,
    val cm3: String,
    val location: String,
    val brand: String,
    val filter_button_text: String,
    val clear_button_text: String,
    val vehicles: String,
    val restaurant_city: String,
    val restaurant_price: String,
    val restaurant_food: String,
    val open_in_maps: String,
    val beach_city: String,
    val beach_parking: String,
    val trip_duration: String,
    val trip_label: String,
    val no_results_found: String,
    val request_offer_button: String,
    val route_label: String,
    val sights_label: String,
    val ferryTitle: String,
    val ferryRoute1Title: String,
    val ferryRoute1Detail1: String,
    val ferryRoute1Detail2: String,
    val ferryRoute1Detail3: String,
    val ferryRoute2Title: String,
    val ferryRoute2Detail1: String,
    val ferryRoute2Detail2: String,
    val ferryRoute2Detail3: String,
    val ferryInfoText: String,
    val ferryWebsite: String,
    val map: String,
    val ferries: String,
    val mapLabel: String,
    val highlight_imaret: String,
    val highlight_old_town: String,
    val highlight_ali_house: String,
    val highlight_tobacco_museum: String,
    val kavala_castle_desc: String,
    val kavala_aqueduct_desc: String,
    val kavala_port_desc: String,
    val prinosKavalaInfo: String,
    val reachThassos: String,
    val reachThassosTitle: String,
    val routeBudapest: String,
    val tollsHungary: String,
    val buyHere: String,
    val restBudapest: String,
    val routeBucharest: String,
    val tollsBulgaria: String,
    val restBucharest: String,
    val routeSofia: String,
    val tollsGreece: String,
    val routeBudapestAlt: String,
    val tollsNorthMacedonia: String,
    val restBudapestAlt: String,
    val restBudapestTip: String
)

val enStrings = Strings(
    appName = "Thassos Vehicle Finder",
    scooter = "Scooters",
    restaurants = "Restaurants",
    beaches = "Beaches",
    vehicle_type = "Vehicle Type",
    cm3 = "cm³",
    location = "Location",
    brand = "Brand",
    filter_button_text = "Filter",
    clear_button_text = "Clear",
    vehicles = "Vehicles",
    restaurant_city = "City",
    restaurant_price = "Price category",
    restaurant_food = "Cuisine",
    open_in_maps = "Open in Google Maps",
    beach_city = "City",
    beach_parking = "Parking",
    trip_duration = "Duration",
    no_results_found = "No results match the selected filters.",
    trip_label = "Trips",
    request_offer_button = "Request Offer",
    route_label = "Route",
    sights_label = "Sights",
    ferryTitle = "🚢 Ferry routes and information",
ferryRoute1Title = "Keramoti ↔ Limenas (Thassos Town)",
ferryRoute1Detail1 = "🕓 In high season every 30–45 min",
ferryRoute1Detail2 = "⏱️ Avg. duration: 35–40 min",
ferryRoute1Detail3 = "🎫 Price: ~5 €, children 3 €",
ferryRoute2Title = "Kavala ↔ Skala Prinos",
ferryRoute2Detail1 = "🕓 4–5 trips per day",
ferryRoute2Detail2 = "⏱️ Duration: ~75 min",
ferryRoute2Detail3 = "🎫 Price: ~6.50 € per person",
ferryInfoText = "ℹ️ For the latest schedule, click here:",
ferryWebsite = "www.thassos-ferries.gr",
    map = "Map",
    ferries = "Ferries",
    mapLabel = "Map",
    kavala_castle_desc = "🏰 Enjoy panoramic views of the city and sea from this Byzantine-era fortress.",
    kavala_aqueduct_desc = "⛲ Stunning 16th-century aqueduct that defines the city's skyline.",
    kavala_port_desc = "🚤 Lively waterfront with boats, cafés, and sunset views.",
    highlight_imaret = "Historic Islamic complex now a luxury hotel.",
    highlight_old_town = "Charming alleys and traditional houses.",
    highlight_ali_house = "18th-century mansion and museum.",
    highlight_tobacco_museum = "Tells the story of Kavala's tobacco heritage.",
    prinosKavalaInfo = "🛳️ Map: Prinos ↔ Kavala — ideal for a day trip (even on foot).",
    reachThassos = "Reach",
    reachThassosTitle = "How to reach Thassos",
    routeBudapest = "Route: Budapest – Szeged – Röszke – Belgrade – Niš – Sofia – Kavala – Keramoti (ferry)",
    tollsHungary = "Tolls:\n• Hungary: e-vignette",
    buyHere = "Buy here",
    routeBucharest = "Route: Bucharest – Ruse – Sofia – Kavala – Keramoti (ferry)",
    tollsBulgaria = "Tolls:\n• Bulgaria: e-vignette",
    restBucharest = "• Greece: toll gates",
    routeSofia = "Route: Sofia – Sandanski – Kavala – Keramoti (ferry)",
    tollsGreece = "Tolls:\n• Greece: toll gates",
    routeBudapestAlt = "Route: Budapest – Szeged – Röszke – Belgrade – Skopje – Thessaloniki – Kavala – Keramoti (ferry)",
    tollsNorthMacedonia = "Tolls:\n• Serbia: toll gates\n• North Macedonia: toll gates\n• Greece: toll gates",
    restBudapestAlt = "Alternative route via North Macedonia.\n✅ Often faster than via Sofia.\n🚗 Mostly highway. Border crossing Serbia–North Macedonia is usually smooth.\n\nRecommended if you want to avoid the winding Niš–Sofia section.",
    restBudapest = "• Serbia: toll gates\n• Bulgaria: e-vignette",
    restBudapestTip = "• Greece: toll gates\n\nTip: The section between Niš and Sofia is slower and winding."
    )

val huStrings = Strings(
    appName = "Thassos Járműkereső",
    scooter = "Robogók",
    restaurants = "Étterem",
    beaches = "Strandok",
    vehicle_type = "Járműtípus",
    cm3 = "Köbcenti",
    location = "Helyszín",
    brand = "Márka",
    filter_button_text = "Szűrés",
    clear_button_text = "Törlés",
    vehicles = "Járművek",
    restaurant_city = "Város",
    restaurant_price = "Árkategória",
    restaurant_food = "Konyha",
    open_in_maps = "Megnyitás Google Maps-en",
    beach_city = "Város",
    beach_parking = "Parkoló",
    trip_duration = "Időtartam",
    no_results_found = "Nincs találat a megadott szűrési feltételekkel.",
    trip_label = "Kirándulások",
    request_offer_button = "Ajánlatkérés",
    route_label = "Útvonal",
    sights_label = "Látnivalók",
    ferryTitle = "🚢 Hajózási útvonalak és információk",
ferryRoute1Title = "Keramoti ↔ Limenas (Thassos Town)",
ferryRoute1Detail1 = "🕓 Főszezonban 30–45 percenként indulnak",
ferryRoute1Detail2 = "⏱️ Átlagos menetidő: 35–40 perc",
ferryRoute1Detail3 = "🎫 Jegyár: kb. 5 €, gyermekeknek 3 €",
ferryRoute2Title = "Kavala ↔ Skala Prinos",
ferryRoute2Detail1 = "🕓 Naponta 4–5 járat",
ferryRoute2Detail2 = "⏱️ Menetidő: kb. 75 perc",
ferryRoute2Detail3 = "🎫 Jegyár: kb. 6,50 € fejenként",
ferryInfoText = "ℹ️ Az aktuális menetrend megtekintéséhez kattints ide:",
ferryWebsite = "www.thassos-ferries.gr",
    map = "Térkép",
    ferries = "Kompok",
    mapLabel = "Térkép",
    kavala_castle_desc = "🏰 Panorámás kilátás a városra és a tengerre a bizánci erődítményből.",
    kavala_aqueduct_desc = "⛲ Lenyűgöző 16. századi vízvezeték, Kavala egyik jelképe.",
    kavala_port_desc = "🚤 Hangulatos kikötő csónakokkal, kávézókkal és naplementével.",
    highlight_imaret = "Történelmi iszlám épület, ma luxusszálloda.",
    highlight_old_town = "Kacskaringós utcák és hagyományos házak.",
    highlight_ali_house = "18. századi kúria, jelenleg múzeum.",
    highlight_tobacco_museum = "Kavala dohányipari múltját bemutató múzeum.",
    prinosKavalaInfo = "🛳️ Térkép: Prinos ↔ Kavala — ideális egynapos kirándulásra (akár gyalog is).",
    reachThassos = "Útvonal",
    reachThassosTitle = "Hogyan juthatsz el Thassosra",
    routeBudapest = "Útvonal: Budapest – Szeged – Röszke – Belgrád – Niš – Szófia – Kavala – Keramoti (komp)",
    tollsHungary = "Díjak:\n• Magyarország: e-matrica",
    buyHere = "Vásárlás itt",
    routeBucharest = "Útvonal: Bukarest – Rusze – Szófia – Kavala – Keramoti (komp)",
    tollsBulgaria = "Díjak:\n• Bulgária: e-matrica",
    restBucharest = "• Görögország: fizetőkapuk",
    routeSofia = "Útvonal: Szófia – Szandanszki – Kavala – Keramoti (komp)",
    tollsGreece = "Díjak:\n• Görögország: fizetőkapuk",
    routeBudapestAlt = "Útvonal: Budapest – Szeged – Röszke – Belgrád – Szkopje – Thesszaloniki – Kavala – Keramoti (komp)",
    tollsNorthMacedonia = "Díjak:\n• Szerbia: fizetőkapuk\n• Észak-Macedónia: fizetőkapuk\n• Görögország: fizetőkapuk",
    restBudapestAlt = "Alternatív útvonal Észak-Macedónián keresztül.\n✅ Gyakran gyorsabb, mint a Szófián át vezető út.\n🚗 Végig autópályás szakaszok, jó minőségű út.\n\nAjánlott, ha elkerülnéd a Niš–Szófia szűk és kanyargós részt.",
    restBudapest = "• Szerbia: fizetőkapuk\n• Bulgária: e-matrica",
    restBudapestTip = "• Görögország: fizetőkapuk\n\nTipp: A Niš–Szófia szakasz lassabb és kanyargós."
)

val bgStrings = Strings(
    appName = "Тасос Превозни средства",
    scooter = "Скутери",
    restaurants = "Ресторанти",
    beaches = "Плажове",
    vehicle_type = "Тип превозно средство",
    cm3 = "см³",
    location = "Местоположение",
    brand = "Марка",
    filter_button_text = "Филтрирай",
    clear_button_text = "Изчисти",
    vehicles = "Превозни средства",
    restaurant_city = "Град",
    restaurant_price = "Ценова категория",
    restaurant_food = "Кухня",
    open_in_maps = "Отвори в Google Maps",
    beach_city = "Град",
    beach_parking = "Паркинг",
    trip_duration = "Продължителност",
    no_results_found = "Няма резултати, отговарящи на избраните филтри.",
    trip_label = "Екскурзии",
    request_offer_button = "Заявка за оферта",
    route_label = "Маршрут",
    sights_label = "Забележителности",
    ferryTitle = "🚢 Фериботни маршрути и информация",
ferryRoute1Title = "Керамоти ↔ Лименас (Тасос Таун)",
ferryRoute1Detail1 = "🕓 В разгара на сезона на всеки 30–45 минути",
ferryRoute1Detail2 = "⏱️ Средна продължителност: 35–40 минути",
ferryRoute1Detail3 = "🎫 Билет: около 5 €, за деца 3 €",
ferryRoute2Title = "Кавала ↔ Скала Принос",
ferryRoute2Detail1 = "🕓 4–5 пътувания дневно",
ferryRoute2Detail2 = "⏱️ Продължителност: около 75 минути",
ferryRoute2Detail3 = "🎫 Билет: около 6,50 € на човек",
ferryInfoText = "ℹ️ За актуално разписание, кликнете тук:",
ferryWebsite = "www.thassos-ferries.gr",
    map = "Карта",
    ferries = "Фериботи",
    mapLabel = "Карта",
    kavala_castle_desc = "🏰 Панорамна гледка към града и морето от византийската крепост.",
    kavala_aqueduct_desc = "⛲ Впечатляващ акведукт от 16 век – символ на Кавала.",
    kavala_port_desc = "🚤 Живо пристанище с лодки, кафенета и залези.",
    highlight_imaret = "Исторически ислямски комплекс, днес луксозен хотел.",
    highlight_old_town = "Очарователни улички и традиционни къщи.",
    highlight_ali_house = "Имение от 18-ти век, днес музей.",
    highlight_tobacco_museum = "Разказва историята на тютюневата индустрия в Кавала.",
    prinosKavalaInfo = "🛳️ Карта: Принос ↔ Кавала — идеално за еднодневна разходка (дори пеша).",
    reachThassos = "Достъп",
    reachThassosTitle = "Как да стигнете до Тасос",
    routeBudapest = "Маршрут: Будапеща – Сегед – Рьошке – Белград – Ниш – София – Кавала – Керамоти (ферибот)",
    tollsHungary = "Такси:\n• Унгария: електронна винетка",
    buyHere = "Купи оттук",
    routeBucharest = "Маршрут: Букурещ – Русе – София – Кавала – Керамоти (ферибот)",
    tollsBulgaria = "Такси:\n• България: електронна винетка",
    restBucharest = "• Гърция: тол такси",
    routeSofia = "Маршрут: София – Сандански – Кавала – Керамоти (ферибот)",
    tollsGreece = "Такси:\n• Гърция: тол такси",
    routeBudapestAlt = "Маршрут: Будапеща – Сегед – Рьошке – Белград – Скопие – Солун – Кавала – Керамоти (ферибот)",
    tollsNorthMacedonia = "Такси:\n• Сърбия: тол такси\n• Северна Македония: тол такси\n• Гърция: тол такси",
    restBudapestAlt = "Алтернативен маршрут през Северна Македония.\n✅ Често по-бърз от маршрута през София.\n🚗 Предимно магистрали. Пресичането на границата Сърбия–С. Македония обикновено е безпроблемно.\n\nПрепоръчва се, ако искате да избегнете тесния и криволичещ участък между Ниш и София.",
    restBudapest = "• Сърбия: тол такси\n• България: електронна винетка",
    restBudapestTip = "• Гърция: тол такси\n\nСъвет: Участъкът между Ниш и София е по-бавен и с много завои."
    )

val roStrings = Strings(
    appName = "Căutare Vehicule Thassos",
    scooter = "Scutere",
    restaurants = "Restaurante",
    beaches = "Plaje",
    vehicle_type = "Tip vehicul",
    cm3 = "cm³",
    location = "Locație",
    brand = "Marcă",
    filter_button_text = "Filtrează",
    clear_button_text = "Șterge",
    vehicles = "Vehicule",
    restaurant_city = "Oraș",
    restaurant_price = "Categorie de preț",
    restaurant_food = "Bucătărie",
    open_in_maps = "Deschide în Google Maps",
    beach_city = "Oraș",
    beach_parking = "Parcare",
    trip_duration = "Durată",
    trip_label = "Excursii",
    no_results_found = "Niciun rezultat pentru filtrele selectate.",
    request_offer_button = "Solicită ofertă",
    route_label = "Rută",
    sights_label = "Obiective",
    ferryTitle = "🚢 Rute și informații feribot",
    ferryRoute1Title = "Keramoti ↔ Limenas (Orașul Thassos)",
    ferryRoute1Detail1 = "🕓 În sezonul de vârf: la fiecare 30–45 min",
    ferryRoute1Detail2 = "⏱️ Durată medie: 35–40 min",
    ferryRoute1Detail3 = "🎫 Preț: ~5 €, copii 3 €",
    ferryRoute2Title = "Kavala ↔ Skala Prinos",
    ferryRoute2Detail1 = "🕓 4–5 curse pe zi",
    ferryRoute2Detail2 = "⏱️ Durată: ~75 min",
    ferryRoute2Detail3 = "🎫 Preț: ~6,50 € de persoană",
    ferryInfoText = "ℹ️ Pentru orarul actualizat, accesează:",
    ferryWebsite = "www.thassos-ferries.gr",
    map = "Hartă",
    ferries = "Feriboturi",
    mapLabel = "Hartă",
    kavala_castle_desc = "🏰 Vedere panoramică asupra orașului și mării din cetatea bizantină.",
    kavala_aqueduct_desc = "⛲ Apeduct impresionant din secolul al XVI-lea – simbol al orașului.",
    kavala_port_desc = "🚤 Port animat cu bărci, cafenele și apusuri superbe.",
    highlight_imaret = "Complex islamic istoric, azi hotel de lux.",
    highlight_old_town = "Străduțe pitorești și case tradiționale.",
    highlight_ali_house = "Conac din secolul XVIII, transformat în muzeu.",
    highlight_tobacco_museum = "Prezintă istoria industriei tutunului din Kavala.",
    prinosKavalaInfo = "🛳️ Hartă: Prinos ↔ Kavala — ideal pentru o excursie de o zi (chiar și pe jos).",
    reachThassos = "Acces",
    reachThassosTitle = "Cum ajungi în Thassos",
    routeBudapest = "Traseu: Budapesta – Szeged – Röszke – Belgrad – Niš – Sofia – Kavala – Keramoti (feribot)",
    tollsHungary = "Taxe:\n• Ungaria: e-vinieta",
    buyHere = "Cumpără aici",
    routeBucharest = "Traseu: București – Ruse – Sofia – Kavala – Keramoti (feribot)",
    tollsBulgaria = "Taxe:\n• Bulgaria: e-vinieta",
    restBucharest = "• Grecia: puncte de taxare",
    routeSofia = "Traseu: Sofia – Sandanski – Kavala – Keramoti (feribot)",
    tollsGreece = "Taxe:\n• Grecia: puncte de taxare",
    routeBudapestAlt = "Traseu: Budapesta – Szeged – Röszke – Belgrad – Skopje – Salonic – Kavala – Keramoti (feribot)",
    tollsNorthMacedonia = "Taxe:\n• Serbia: puncte de taxare\n• Macedonia de Nord: puncte de taxare\n• Grecia: puncte de taxare",
    restBudapestAlt = "Rută alternativă prin Macedonia de Nord.\n✅ Adesea mai rapidă decât cea prin Sofia.\n🚗 În mare parte autostradă. Trecerea frontierei Serbia–MK este de obicei rapidă.\n\nRecomandat dacă vrei să eviți porțiunea sinuoasă dintre Niš și Sofia.",
    restBudapest = "• Serbia: puncte de taxare\n• Bulgaria: e-vinieta",
    restBudapestTip = "• Grecia: puncte de taxare\n\nSfaturi: Traseul între Niš și Sofia este mai lent și sinuos."
    )


val LocalStrings = staticCompositionLocalOf { enStrings }
